# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: mos_object.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10mos_object.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\x0f\n\rObjectRequest\"`\n\rStreamingData\x12 \n\x0bobject_data\x18\x01 \x03(\x0b\x32\x0b.ObjectData\x12-\n\ttimestamp\x18\x02 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\"[\n\nObjectData\x12\x11\n\tobject_id\x18\x01 \x01(\x05\x12\x19\n\x04type\x18\x02 \x01(\x0e\x32\x0b.ObjectType\x12\x1f\n\ncoordinate\x18\x03 \x01(\x0b\x32\x0b.Coordinate\"\"\n\nCoordinate\x12\t\n\x01x\x18\x01 \x01(\x01\x12\t\n\x01y\x18\x02 \x01(\x01*\x83\x01\n\nObjectType\x12\x07\n\x03\x43\x61r\x10\x00\x12\x07\n\x03\x42us\x10\x01\x12\t\n\x05Truck\x10\x02\x12\x15\n\x11\x41utonomousVehicle\x10\x03\x12\x0b\n\x07\x42icycle\x10\x04\x12\x0e\n\nMotorcycle\x10\x05\x12\x14\n\x10PersonalMobility\x10\x06\x12\x0e\n\nPedestrian\x10\x07\x32G\n\rObjectService\x12\x36\n\x10streaming_object\x12\x0e.ObjectRequest\x1a\x0e.StreamingData\"\x00\x30\x01\x62\x06proto3')

_OBJECTTYPE = DESCRIPTOR.enum_types_by_name['ObjectType']
ObjectType = enum_type_wrapper.EnumTypeWrapper(_OBJECTTYPE)
Car = 0
Bus = 1
Truck = 2
AutonomousVehicle = 3
Bicycle = 4
Motorcycle = 5
PersonalMobility = 6
Pedestrian = 7


_OBJECTREQUEST = DESCRIPTOR.message_types_by_name['ObjectRequest']
_STREAMINGDATA = DESCRIPTOR.message_types_by_name['StreamingData']
_OBJECTDATA = DESCRIPTOR.message_types_by_name['ObjectData']
_COORDINATE = DESCRIPTOR.message_types_by_name['Coordinate']
ObjectRequest = _reflection.GeneratedProtocolMessageType('ObjectRequest', (_message.Message,), {
  'DESCRIPTOR' : _OBJECTREQUEST,
  '__module__' : 'mos_object_pb2'
  # @@protoc_insertion_point(class_scope:ObjectRequest)
  })
_sym_db.RegisterMessage(ObjectRequest)

StreamingData = _reflection.GeneratedProtocolMessageType('StreamingData', (_message.Message,), {
  'DESCRIPTOR' : _STREAMINGDATA,
  '__module__' : 'mos_object_pb2'
  # @@protoc_insertion_point(class_scope:StreamingData)
  })
_sym_db.RegisterMessage(StreamingData)

ObjectData = _reflection.GeneratedProtocolMessageType('ObjectData', (_message.Message,), {
  'DESCRIPTOR' : _OBJECTDATA,
  '__module__' : 'mos_object_pb2'
  # @@protoc_insertion_point(class_scope:ObjectData)
  })
_sym_db.RegisterMessage(ObjectData)

Coordinate = _reflection.GeneratedProtocolMessageType('Coordinate', (_message.Message,), {
  'DESCRIPTOR' : _COORDINATE,
  '__module__' : 'mos_object_pb2'
  # @@protoc_insertion_point(class_scope:Coordinate)
  })
_sym_db.RegisterMessage(Coordinate)

_OBJECTSERVICE = DESCRIPTOR.services_by_name['ObjectService']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _OBJECTTYPE._serialized_start=298
  _OBJECTTYPE._serialized_end=429
  _OBJECTREQUEST._serialized_start=53
  _OBJECTREQUEST._serialized_end=68
  _STREAMINGDATA._serialized_start=70
  _STREAMINGDATA._serialized_end=166
  _OBJECTDATA._serialized_start=168
  _OBJECTDATA._serialized_end=259
  _COORDINATE._serialized_start=261
  _COORDINATE._serialized_end=295
  _OBJECTSERVICE._serialized_start=431
  _OBJECTSERVICE._serialized_end=502
# @@protoc_insertion_point(module_scope)
